image: openjdk:8-jdk

stages:
  - build
  - docs

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - java -version

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew assemble
    - ./gradlew check
  except:
    - gh-pages

docs:
  stage: docs
  script:
    - ./gradlew dokka
    - chmod +x deploy-docs.sh
    - ./deploy-docs.sh
  only:
    - master

after_script:
  - echo "End CI"
